# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_company_bank_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=16, unique=True, verbose_name='Currency')),
                ('bank_account_number', models.CharField(blank=True, max_length=512, null=True, verbose_name='Bank account number')),
                ('iban', models.CharField(blank=True, max_length=512, null=True, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Bank name')),
                ('bank_branch', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Bank branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='bank_account_number',
        ),
        migrations.AlterField(
            model_name='company',
            name='address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_country',
            field=models.CharField(blank=True, choices=[('AF', 'Afganistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AD', 'Andora'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarktyda'), ('AG', 'Antigua i Barbuda'), ('SA', 'Arabia Saudyjska'), ('AR', 'Argentyna'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbejdżan'), ('BS', 'Bahamy'), ('BH', 'Bahrajn'), ('BD', 'Bangladesz'), ('BB', 'Barbados'), ('BE', 'Belgia'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermudy'), ('BT', 'Bhutan'), ('BY', 'Białoruś'), ('BO', 'Boliwia'), ('BQ', 'Bonaire, Sint Eustatius i Saba'), ('BA', 'Bośnia i Hercegowina'), ('BW', 'Botswana'), ('BR', 'Brazylia'), ('BN', 'Brunei'), ('IO', 'Brytyjskie Terytorium Oceanu Indyjskiego'), ('VG', 'Brytyjskie Wyspy Dziewicze'), ('BG', 'Bułgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CL', 'Chile'), ('CN', 'Chiny'), ('HR', 'Chorwacja'), ('CW', 'Curaçao'), ('CY', 'Cypr'), ('TD', 'Czad'), ('ME', 'Czarnogóra'), ('CZ', 'Czechy'), ('UM', 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych'), ('DK', 'Dania'), ('DM', 'Dominika'), ('DO', 'Dominikana'), ('DJ', 'Dżibuti'), ('EG', 'Egipt'), ('EC', 'Ekwador'), ('ER', 'Erytrea'), ('EE', 'Estonia'), ('ET', 'Etiopia'), ('FK', 'Falklandy'), ('FJ', 'Fidżi'), ('PH', 'Filipiny'), ('FI', 'Finlandia'), ('FR', 'Francja'), ('TF', 'Francuskie Terytoria Południowe i Antarktyczne'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GS', 'Georgia Południowa i Sandwich Południowy'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Grecja'), ('GD', 'Grenada'), ('GL', 'Grenlandia'), ('GE', 'Gruzja'), ('GU', 'Guam'), ('GG', 'Guernsey'), ('GY', 'Gujana'), ('GF', 'Gujana Francuska'), ('GP', 'Gwadelupa'), ('GT', 'Gwatemala'), ('GN', 'Gwinea'), ('GW', 'Gwinea Bissau'), ('GQ', 'Gwinea Równikowa'), ('HT', 'Haiti'), ('ES', 'Hiszpania'), ('NL', 'Holandia'), ('VA', 'Holy See'), ('HN', 'Honduras'), ('HK', 'Hongkong'), ('IN', 'Indie'), ('ID', 'Indonezja'), ('IQ', 'Irak'), ('IR', 'Iran'), ('IE', 'Irlandia'), ('IS', 'Islandia'), ('IL', 'Izrael'), ('JM', 'Jamajka'), ('JP', 'Japonia'), ('YE', 'Jemen'), ('JE', 'Jersey'), ('JO', 'Jordania'), ('KY', 'Kajmany'), ('KH', 'Kambodża'), ('CM', 'Kamerun'), ('CA', 'Kanada'), ('QA', 'Katar'), ('KZ', 'Kazachstan'), ('KE', 'Kenia'), ('KG', 'Kirgistan'), ('KI', 'Kiribati'), ('CO', 'Kolumbia'), ('KM', 'Komory'), ('CD', 'Kongo'), ('CG', 'Kongo'), ('KP', 'Korea Północna'), ('KR', 'Korea Południowa'), ('CR', 'Kostaryka'), ('CU', 'Kuba'), ('KW', 'Kuwejt'), ('LA', 'Laos'), ('LS', 'Lesotho'), ('LB', 'Liban'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Litwa'), ('LU', 'Luksemburg'), ('MK', 'Macedonia'), ('MG', 'Madagaskar'), ('YT', 'Majotta'), ('MO', 'Makau'), ('MW', 'Malawi'), ('MV', 'Malediwy'), ('MY', 'Malezja'), ('ML', 'Mali'), ('MT', 'Malta'), ('MP', 'Mariany Północne'), ('MA', 'Maroko'), ('MQ', 'Martynika'), ('MR', 'Mauretania'), ('MU', 'Mauritius'), ('MX', 'Meksyk'), ('FM', 'Micronesia (Federated States of)'), ('MM', 'Mjanma'), ('MD', 'Moldova'), ('MC', 'Monako'), ('MN', 'Mongolia'), ('MS', 'Montserrat'), ('MZ', 'Mozambik'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('DE', 'Niemcy'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NI', 'Nikaragua'), ('NU', 'Niue'), ('NF', 'Norfolk'), ('NO', 'Norwegia'), ('NC', 'Nowa Kaledonia'), ('NZ', 'Nowa Zelandia'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestyna'), ('PA', 'Panama'), ('PG', 'Papua-Nowa Gwinea'), ('PY', 'Paragwaj'), ('PE', 'Peru'), ('PN', 'Pitcairn'), ('PF', 'Polinezja Francuska'), ('PL', 'Polska'), ('PR', 'Portoryko'), ('PT', 'Portugalia'), ('ZA', 'Republika Południowej Afryki'), ('CF', 'Republika Środkowoafrykańska'), ('CV', 'Republika Zielonego Przylądka'), ('RE', 'Reunion'), ('RU', 'Rosja'), ('RO', 'Rumunia'), ('RW', 'Rwanda'), ('EH', 'Sahara Zachodnia'), ('KN', 'Saint Kitts i Nevis'), ('LC', 'Saint Lucia'), ('VC', 'Saint Vincent i Grenadyny'), ('BL', 'Saint-Barthélemy'), ('MF', 'Saint-Martin'), ('PM', 'Saint-Pierre i Miquelon'), ('SV', 'Salwador'), ('WS', 'Samoa'), ('AS', 'Samoa Amerykańskie'), ('SM', 'San Marino'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seszele'), ('SL', 'Sierra Leone'), ('SG', 'Singapur'), ('SX', 'Sint Maarten'), ('SO', 'Somalia'), ('SK', 'Słowacja'), ('SI', 'Słowenia'), ('LK', 'Sri Lanka'), ('SZ', 'Suazi'), ('SD', 'Sudan'), ('SS', 'Sudan Południowy'), ('SR', 'Surinam'), ('SJ', 'Svalbard i Jan Mayen'), ('SY', 'Syria'), ('CH', 'Szwajcaria'), ('SE', 'Szwecja'), ('TJ', 'Tadżykistan'), ('TH', 'Tajlandia'), ('TW', 'Tajwan'), ('TZ', 'Tanzania'), ('TL', 'Timor Wschodni'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trynidad i Tobago'), ('TN', 'Tunezja'), ('TR', 'Turcja'), ('TM', 'Turkmenistan'), ('TC', 'Turks i Caicos'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraina'), ('US', 'United States of America'), ('UY', 'Urugwaj'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('WF', 'Wallis i Futuna'), ('HU', 'Węgry'), ('VE', 'Wenezuela'), ('GB', 'Wielka Brytania'), ('VN', 'Wietnam'), ('IT', 'Włochy'), ('CI', 'Wybrzeże Kości Słoniowej'), ('BV', 'Wyspa Bouveta'), ('CX', 'Wyspa Bożego Narodzenia'), ('IM', 'Wyspa Man'), ('SH', 'Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha'), ('AX', 'Wyspy Alandzkie'), ('CK', 'Wyspy Cooka'), ('VI', 'Wyspy Dziewicze Stanów Zjednoczonych'), ('HM', 'Wyspy Heard i McDonalda'), ('CC', 'Wyspy Kokosowe'), ('MH', 'Wyspy Marshalla'), ('FO', 'Wyspy Owcze'), ('SB', 'Wyspy Salomona'), ('ST', 'Wyspy Świętego Tomasza i Książęca'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('AE', 'Zjednoczone Emiraty Arabskie'), ('LV', 'Łotwa')], max_length=512, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Company'),
        ),
    ]
