# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20181207_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybankaccount',
            old_name='currency',
            new_name='slug',
        ),
    ]
