# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20181207_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankaccount',
            name='slug',
            field=models.CharField(max_length=16, unique=True, verbose_name='Short name'),
        ),
    ]
