# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_companybankaccount_swift'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='sorting_number',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Sorting number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_nip',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='NIP'),
        ),
    ]
