# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Series name')),
                ('pattern', models.CharField(max_length=128, verbose_name='Series pattern')),
                ('mode', models.IntegerField(choices=[(0, 'Numbered yearly')], verbose_name='Mode')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoiceSeries'),
            preserve_default=False,
        ),
    ]
