# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20160109_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Invoice number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceseries',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Numbered monthly'), (1, 'Numbered yearly')], verbose_name='Mode'),
        ),
    ]
