# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20160109_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_delivered',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now, verbose_name='Delivery date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now, verbose_name='Issue date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(default=0, verbose_name='Invoice number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(verbose_name='Invoice internal number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoiceSeries'),
        ),
    ]
