# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20160109_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_delivered',
            field=models.DateField(default=datetime.datetime(2016, 1, 9, 10, 41, 51, 584705), verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(default=datetime.datetime(2016, 1, 9, 10, 41, 51, 584601), verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=128, verbose_name='Invoice number'),
        ),
    ]
