# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20160109_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceposition',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
