# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20160110_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Bank transfer'), (1, 'PayPal')], default=0, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='money_net',
            field=models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Price net'),
        ),
    ]
