# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-07 14:30
from __future__ import unicode_literals

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20160110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.invoices.models.Invoice.generate_filename, verbose_name='Invoice'),
        ),
    ]
