# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20181207_1443'),
        ('invoices', '0013_auto_20181207_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.CompanyBankAccount'),
        ),
    ]
