# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoice_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='Value')),
            ],
        ),
    ]
