# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='display',
            field=models.CharField(default='-', max_length=128, verbose_name='Display'),
            preserve_default=False,
        ),
    ]
