# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_auto_20181227_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='fulls_name_dative',
            field=models.CharField(max_length=128, verbose_name='Fulls name (dative)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='fulls_name_denominator',
            field=models.CharField(max_length=128, verbose_name='Fulls name (denominator)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='fulls_name_genitive',
            field=models.CharField(max_length=128, verbose_name='Fulls name (genitive)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='halves_name_dative',
            field=models.CharField(max_length=128, verbose_name='Halves name (dative)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='halves_name_denominator',
            field=models.CharField(max_length=128, verbose_name='Halves name (denominator)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='halves_name_genitive',
            field=models.CharField(max_length=128, verbose_name='Halves name (genitive)'),
        ),
    ]
