# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_auto_20181227_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
