# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-27 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_auto_20181227_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate_url',
        ),
    ]
