# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_remove_currency_exchange_rate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
