# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('invoice-instalment', 'Instalment invoice'), ('invoice-final', 'Final invoice'), ('invoice-proforma', 'Request for payment')], default='invoice', max_length=64, verbose_name='Invoice type'),
            preserve_default=False,
        ),
    ]
