# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-12-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20160329_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='If you leave this field blank, it will be filled in automatically.', max_digits=32, verbose_name='Total costs'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='income_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='If you leave this field blank, it will be filled in automatically.', max_digits=32, verbose_name='Total income'),
        ),
    ]
